using Gradio.Net.Components;

namespace Gradio.Net;

public static partial class gr
{
    public static Chatbot Chatbot(
        object value = null,
        string label = null,
        object every = null,
        object inputs = null,
        bool? showLabel = null,
        bool container = true,
        int? scale = null,
        int minWidth = 160,
        object visible = null,
        string elemId = null,
        object elemClasses = null,
        bool autoscroll = true,
        bool render = true,
        object key = null,
        object preservedByKey = null,
        object height = null,
        bool resizable = false,
        object maxHeight = null,
        object minHeight = null,
        string editable = null,
        List<Dictionary<string, object>> latexDelimiters = null,
        bool rtl = false,
        List<string> buttons = null,
        string watermark = null,
        Tuple<object, object> avatarImages = null,
        bool sanitizeHtml = true,
        bool renderMarkdown = true,
        object feedbackOptions = null,
        object feedbackValue = null,
        bool lineBreaks = true,
        string layout = null,
        string placeholder = null,
        List<ExampleMessage> examples = null,
        bool allowFileDownloads = true,
        bool groupConsecutiveMessages = true,
        object allowTags = null,
        List<Tuple<string, string>> reasoningTags = null,
        bool likeUserMessage = false)
    {
        return new Chatbot(
            value: value,
            label: label,
            every: every,
            inputs: inputs,
            showLabel: showLabel,
            container: container,
            scale: scale,
            minWidth: minWidth,
            visible: visible,
            elemId: elemId,
            elemClasses: elemClasses,
            autoscroll: autoscroll,
            render: render,
            key: key,
            preservedByKey: preservedByKey,
            height: height,
            resizable: resizable,
            maxHeight: maxHeight,
            minHeight: minHeight,
            editable: editable,
            latexDelimiters: latexDelimiters,
            rtl: rtl,
            buttons: buttons,
            watermark: watermark,
            avatarImages: avatarImages,
            sanitizeHtml: sanitizeHtml,
            renderMarkdown: renderMarkdown,
            feedbackOptions: feedbackOptions,
            feedbackValue: feedbackValue,
            lineBreaks: lineBreaks,
            layout: layout,
            placeholder: placeholder,
            examples: examples,
            allowFileDownloads: allowFileDownloads,
            groupConsecutiveMessages: groupConsecutiveMessages,
            allowTags: allowTags,
            reasoningTags: reasoningTags,
            likeUserMessage: likeUserMessage);
    }
}
