using Gradio.Net.Components;

namespace Gradio.Net;

public static partial class gr
{
    public static Dataframe Dataframe(
        object value = null,
        List<string> headers = null,
        object rowCount = null,
        (int? Min, int? Max)? rowLimits = null,
        object columnCount = null,
        (int? Min, int? Max)? columnLimits = null,
        object datatype = null,
        string type = "pandas",
        List<Dictionary<string, object>> latexDelimiters = null,
        string label = null,
        bool? showLabel = null,
        object every = null,
        object inputs = null,
        object maxHeight = null,
        int? scale = null,
        int minWidth = 160,
        bool? interactive = null,
        object visible = null,
        string elemId = null,
        object elemClasses = null,
        bool render = true,
        object key = null,
        object preservedByKey = null,
        bool wrap = false,
        bool lineBreaks = true,
        List<object> columnWidths = null,
        List<string> buttons = null,
        bool showRowNumbers = false,
        int? maxChars = null,
        string showSearch = "none",
        int? pinnedColumns = null,
        List<int> staticColumns = null)
    {
        return new Dataframe(
            value: value,
            headers: headers,
            rowCount: rowCount,
            rowLimits: rowLimits,
            columnCount: columnCount,
            columnLimits: columnLimits,
            datatype: datatype,
            type: type,
            latexDelimiters: latexDelimiters,
            label: label,
            showLabel: showLabel,
            every: every,
            inputs: inputs,
            maxHeight: maxHeight,
            scale: scale,
            minWidth: minWidth,
            interactive: interactive,
            visible: visible,
            elemId: elemId,
            elemClasses: elemClasses,
            render: render,
            key: key,
            preservedByKey: preservedByKey,
            wrap: wrap,
            lineBreaks: lineBreaks,
            columnWidths: columnWidths,
            buttons: buttons,
            showRowNumbers: showRowNumbers,
            maxChars: maxChars,
            showSearch: showSearch,
            pinnedColumns: pinnedColumns,
            staticColumns: staticColumns);
    }
}
