using Gradio.Net.Components;
using Gradio.Net.Core;

namespace Gradio.Net;

public static partial class gr
{
    public static Interface Interface(
        Delegate fn,
        object inputs,
        object outputs,
        string? title = null,
        string? description = null,
        object? examples = null,
        bool? cacheExamples = null,
        string? cacheMode = null,
        int examplesPerPage = 10,
        int? preloadExample = 0,
        bool live = false,
        string? article = null,
        string? flaggingMode = null,
        List<string>? flaggingOptions = null,
        string flaggingDir = ".gradio/flagged",
        bool? analyticsEnabled = null,
        bool batch = false,
        int maxBatchSize = 4,
        string apiVisibility = "public",
        string? apiName = "predict",
        string? apiDescription = null,
        bool allowDuplication = false,
        string concurrencyLimit = "default",
        object? additionalInputs = null,
        object? additionalInputsAccordion = null,
        string submitBtn = "Submit",
        string stopBtn = "Stop",
        string? clearBtn = "Clear",
        (int frequency, int age)? deleteCache = null,
        string showProgress = "full",
        bool fillWidth = false,
        int? timeLimit = 30,
        double streamEvery = 0.5,
        object? deepLink = null,
        Delegate? validator = null)
    {
        return new Interface(
            fn,
            inputs,
            outputs,
            examples,
            cacheExamples,
            cacheMode,
            examplesPerPage,
            null,
            preloadExample,
            live,
            title,
            description,
            article,
            flaggingMode,
            flaggingOptions,
            flaggingDir,
            null,
            analyticsEnabled,
            batch,
            maxBatchSize,
            apiVisibility,
            apiName,
            apiDescription,
            false,
            allowDuplication,
            concurrencyLimit,
            additionalInputs,
            additionalInputsAccordion,
            submitBtn,
            stopBtn,
            clearBtn,
            deleteCache != null ? new Tuple<int, int>(deleteCache.Value.frequency, deleteCache.Value.age) : null,
            showProgress,
            fillWidth,
            timeLimit,
            streamEvery,
            deepLink,
            validator);
    }
}
