using Gradio.Net.Events;

namespace Gradio.Net;

public static partial class gr
{
    public static Dependency On(
        List<TriggerBinding>? triggers = null,
        Delegate? fn = null,
        object? inputs = null,
        object? outputs = null,
        string apiVisibility = "public",
        string? apiName = null,
        object? apiDescription = null,
        bool scrollToOutput = false,
        string showProgress = "full",
        object? showProgressOn = null,
        bool queue = true,
        bool batch = false,
        int maxBatchSize = 4,
        bool preprocess = true,
        bool postprocess = true,
        List<int>? cancels = null,
        string? triggerMode = null,
        string? js = null,
        object? concurrencyLimit = null,
        string? concurrencyId = null,
        int? timeLimit = null,
        float streamEvery = 0.5f,
        object? key = null,
        Delegate? validator = null)
        => Events.Events.On(
            triggers: triggers,
            fn: fn,
            inputs: inputs,
            outputs: outputs,
            apiVisibility: apiVisibility,
            apiName: apiName,
            apiDescription: apiDescription,
            scrollToOutput: scrollToOutput,
            showProgress: showProgress,
            showProgressOn: showProgressOn,
            queue: queue,
            batch: batch,
            maxBatchSize: maxBatchSize,
            preprocess: preprocess,
            postprocess: postprocess,
            cancels: cancels,
            triggerMode: triggerMode,
            js: js,
            concurrencyLimit: concurrencyLimit,
            concurrencyId: concurrencyId,
            timeLimit: timeLimit,
            streamEvery: streamEvery,
            key: key,
            validator: validator);

    public static Dependency On(
        List<EventListener>? triggers = null,
        Delegate? fn = null,
        object? inputs = null,
        object? outputs = null,
        string apiVisibility = "public",
        string? apiName = null,
        object? apiDescription = null,
        bool scrollToOutput = false,
        string showProgress = "full",
        object? showProgressOn = null,
        bool queue = true,
        bool batch = false,
        int maxBatchSize = 4,
        bool preprocess = true,
        bool postprocess = true,
        List<int>? cancels = null,
        string? triggerMode = null,
        string? js = null,
        object? concurrencyLimit = null,
        string? concurrencyId = null,
        int? timeLimit = null,
        float streamEvery = 0.5f,
        object? key = null,
        Delegate? validator = null)
        => Events.Events.On(
            triggers: triggers,
            fn: fn,
            inputs: inputs,
            outputs: outputs,
            // Python parity: EventListener sets event_specific_args = event_specific_args or []
            // Ensure empty list is serialized as [] not null for EventListener-based events.
            includeEmptyEventSpecificArgs: true,
            apiVisibility: apiVisibility,
            apiName: apiName,
            apiDescription: apiDescription,
            scrollToOutput: scrollToOutput,
            showProgress: showProgress,
            showProgressOn: showProgressOn,
            queue: queue,
            batch: batch,
            maxBatchSize: maxBatchSize,
            preprocess: preprocess,
            postprocess: postprocess,
            cancels: cancels,
            triggerMode: triggerMode,
            js: js,
            concurrencyLimit: concurrencyLimit,
            concurrencyId: concurrencyId,
            timeLimit: timeLimit,
            streamEvery: streamEvery,
            key: key,
            validator: validator);
}
