using Gradio.Net.Components;

namespace Gradio.Net;

public static partial class gr
{
    public static Textbox Textbox(
        object value = null,
        string label = null,
        object every = null,
        object inputs = null,
        bool? showLabel = null,
        bool container = true,
        int? scale = null,
        int minWidth = 160,
        bool? interactive = null,
        object visible = null,
        string elemId = null,
        object elemClasses = null,
        bool autofocus = false,
        bool render = true,
        object key = null,
        object preservedByKey = null,
        string type = "text",
        int lines = 1,
        int? maxLines = null,
        object placeholder = null,
        List<string> buttons = null,
        object submitBtn = null,
        object stopBtn = null,
        bool autoscroll = true,
        string textAlign = null,
        bool rtl = false,
        int? maxLength = null,
        InputHTMLAttributes htmlAttributes = null,
        string info = null)
    {
        return new Textbox(
            value: value,
            label: label,
            every: every,
            inputs: inputs,
            showLabel: showLabel,
            container: container,
            scale: scale,
            minWidth: minWidth,
            interactive: interactive,
            visible: visible,
            elemId: elemId,
            elemClasses: elemClasses,
            autofocus: autofocus,
            render: render,
            key: key,
            preservedByKey: preservedByKey,
            type: type,
            lines: lines,
            maxLines: maxLines,
            placeholder: placeholder,
            buttons: buttons,
            submitBtn: submitBtn,
            stopBtn: stopBtn,
            autoscroll: autoscroll,
            textAlign: textAlign,
            rtl: rtl,
            maxLength: maxLength,
            htmlAttributes: htmlAttributes,
            info: info);
    }

    public static Textbox TextBox(
        object value = null,
        string label = null,
        object every = null,
        object inputs = null,
        bool? showLabel = null,
        bool container = true,
        int? scale = null,
        int minWidth = 160,
        bool? interactive = null,
        object visible = null,
        string elemId = null,
        object elemClasses = null,
        bool autofocus = false,
        bool render = true,
        object key = null,
        object preservedByKey = null,
        string type = "text",
        int lines = 1,
        int? maxLines = null,
        object placeholder = null,
        List<string> buttons = null,
        object submitBtn = null,
        object stopBtn = null,
        bool autoscroll = true,
        string textAlign = null,
        bool rtl = false,
        int? maxLength = null,
        InputHTMLAttributes htmlAttributes = null)
    {
        return Textbox(
            value: value,
            label: label,
            every: every,
            inputs: inputs,
            showLabel: showLabel,
            container: container,
            scale: scale,
            minWidth: minWidth,
            interactive: interactive,
            visible: visible,
            elemId: elemId,
            elemClasses: elemClasses,
            autofocus: autofocus,
            render: render,
            key: key,
            preservedByKey: preservedByKey,
            type: type,
            lines: lines,
            maxLines: maxLines,
            placeholder: placeholder,
            buttons: buttons,
            submitBtn: submitBtn,
            stopBtn: stopBtn,
            autoscroll: autoscroll,
            textAlign: textAlign,
            rtl: rtl,
            maxLength: maxLength,
            htmlAttributes: htmlAttributes);
    }
}
